### PR TITLE
use Scratch.jl

### PR DESCRIPTION
**Pull request by jbrea**
Addresses #20.
Thanks @maleadt. I didn't know about Scratch.jl. I think this is much cleaner now.

### CODE REVIEW

**Comment by maleadt** [comment]
Yeah, that's better. Is there a reason you don't just encode the datasets as a static Artifacts.toml (you can set them to lazy to avoid downloading them all at package installation time)?

**Comment by jbrea** [comment]
[OpenML has nearly 5k datasets](https://www.openml.org/search?type=data&sort=runs&status=active) right now and new datasets are constantly added. I prefer the `Scratch.jl` approach over having to update an Artifact.toml every time when new datasets are added.

**Comment by maleadt** [comment]
Makes sense! FWIW, the advantage of artifacts is that they are easily cached, while scratchspaces are more ephemeral.

**Comment by jbrea** [comment]
@ablaom I think this is ready to be merged.

**Pull request merged**
